services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
      - .env
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
